### ISSUE TITLE
🚀 Feature: A method for Projects class to update JWT expiration

### ISSUE THREAD

**Issue by MKSinghDev** [appwrite/sdk-for-console#7]
### 🔖 Feature description

There is a feature request https://github.com/appwrite/appwrite/issues/5263 for which we need a separate method on Projects class to update the JWT expiration.

![image](https://github.com/appwrite/sdk-for-console/assets/52215756/5a0cd564-bf46-451d-a3f5-46484c1a0435)

### 🎤 Pitch

I'm interested in working on https://github.com/appwrite/appwrite/issues/5263. So, creating this ticket for referencing it in the PR later. Please let me know if I'm missing something.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Unfortunately, this is a read-only repo as the code is generated by our [SDK Generator](https://github.com/appwrite/sdk-generator), and changes made only here would be wiped in the next release.
